#!/bin/bash

PRG=MultiMarket

LIB_JDM=/dm/dmJava/lib/libjdm/pack/libjdm.jar
LIBS=$LIB_JDM

# -----------------------------------------------------------------------------

compile () {
  javac -cp $LIBS -d classes src/es/dm/*.java
  javac -cp $LIBS:classes -d classes src/multimarket/*.java \
    src/multimarket/sys/*.java \
    src/multimarket/data/*.java
}

pack () {
  rm -fR classes
  mkdir classes
  compile
  if [ -e pack/tmp ]
  then
    rm -fR pack/tmp
  fi
  mkdir pack/tmp
  cd pack/tmp
  jar xvf $LIB_JDM
  cp -fR ../../classes/* ./
  rm -fR META-INF
  mkdir META-INF
  echo 'Manifest-Version: 1.0' > META-INF/MANIFEST.MF
  echo 'Created-By: ºDeme' >> META-INF/MANIFEST.MF
  echo 'Main-Class: multimarket.Main' >> META-INF/MANIFEST.MF
  echo ''>> META-INF/MANIFEST.MF
  jar cvfm ../$PRG.jar META-INF/MANIFEST.MF *
  cd ../..
  rm -fR pack/tmp
}

case $1 in
c)
  compile
  ;;
x)
  compile
  java -cp $LIBS:classes multimarket.Main
  ;;
tests)
  compile
  cd tests
  javac -cp $LIBS:../classes -d classes src/*.java
  java -cp $LIBS:../classes:classes MainTests
  ;;
pack)
  pack
  ;;
run)
  pack
  java -jar pack/$PRG.jar
  ;;
doc)
  javadoc -cp $LIBS -quiet -d api -sourcepath src -linksource multimarket
  ;;
*)
  echo $1: Unknown option
  ;;
esac


