#!/bin/bash

PRG=jsh

LIB_JDM=/dm/dmJava/lib/libjdm/pack/libjdm.jar
LIBS=$LIB_JDM

# -----------------------------------------------------------------------------

pack () {
  rm -fR classes
  mkdir classes
  javac -cp $LIBS -d classes src/*.java
  if [ -e pack/tmp ]
  then
    rm -fR pack/tmp
  fi
  mkdir pack/tmp
  cd pack/tmp
  jar xvf $LIB_JDM
  cp -fR ../../classes/* ./
  rm -fR META-INF
  mkdir META-INF
  echo 'Manifest-Version: 1.0' > META-INF/MANIFEST.MF
  echo 'Created-By: ºDeme' >> META-INF/MANIFEST.MF
  echo 'Main-Class: Main' >> META-INF/MANIFEST.MF
  echo ''>> META-INF/MANIFEST.MF
  jar cvfm ../$PRG.jar META-INF/MANIFEST.MF *
  cd ../..
  rm -fR pack/tmp
}

case $1 in
c*)
  javac -cp $LIBS -d classes src/*.java
  ;;
x*)
  javac -cp $LIBS -d classes src/*.java
  java -cp $LIBS:classes Main
  ;;
pack*)
  pack
  ;;
run*)
  pack
  java -jar pack/$PRG.jar
  ;;
doc*)
  javadoc -quiet -d api -sourcepath src es.dm
  ;;
*)
  echo $1: Unknown option
  ;;
esac


